### ISSUE TITLE
Gratitude and opportunity to collaborate

### ISSUE THREAD

**Issue by Dsgnr-JM** [knadh/dragmove.js#14]
Thank you very much friend for this small but functional library, it was just what I was looking for to implement in my alerts library [BellJS](https://github.com/Dsgnr-JM/bell), it needs something light and you achieved it.

**Comment by knadh** [comment]
Glad that it is of use. Thank you.

**Comment by Dsgnr-JM** [comment]
It was very useful to me, although I could have optimized it a little more.
