### ISSUE TITLE
onEnd functions all fire for every `mouseup` event

### ISSUE THREAD

**Issue by GreyMatteOr** [knadh/dragmove.js#5]
On line 49,

``` JavaScript
  document.addEventListener(_isTouch ? "touchend" : "mouseup", function() {
   /* ... */
  }
```

I think this should be `target` instead of `document`, no? This way, only the functions specific to an element get fired (not for every onEnd ever registered).

**Comment by knadh** [comment]
Hi @GreyMatteOr. Registering on the document is essential because when you click and drag an object quickly, the cursor goes out of the object's boundary and stop propagating events. 

Edit: Oh wait, I see what you mean. You're right. The event should be filtered and fired for just that one target.

**Comment by GreyMatteOr** [comment]
Ah, now I understand the reasoning for using `document`. I must mouse too deliberately to have ever noticed!

I think this filtering method will surely solve both issues.

Cheers!

**Comment by knadh** [comment]
https://github.com/knadh/dragmove.js/commit/0702a4a40f361abfaa5ae9dc35fdd1f94bb3974e fixes this. Thanks.
