### ISSUE TITLE
Uncaught error when build with webpack

### ISSUE THREAD

**Issue by gioppy** [knadh/dragmove.js#8]
Hi,
Using webpack in development (with watch without build and finalization) everything works perfectly. But when I go to build I get this error from the browser: `TypeError: can't access property "addEventListener", (void 0) is undefined `.
I use Laravel Mix for build the assets. I paste here the lines of code I use, maybe I wrote something wrong.
```import { dragmove } from '@knadh/dragmove';

(function () {
  'use strict';

  document.addEventListener('DOMContentLoaded', handleDOMContentLoaded);

  function handleDOMContentLoaded() {
    document.querySelectorAll('.collage__item').forEach(function (el) {
      dragmove(el, el);
    })
  }
})();

**Comment by knadh** [comment]
Looks like `document` is null in the build context. Maybe try debugging by adding a `console.log(document)`?

**Comment by gioppy** [comment]
Hi,
logging the document is correctly found. Very strangely, duplicating your file in my folders and importing it (`import { dragmove } from './dragmove'`) instead of the one in the `node_modules` folder the build is ok.  🤷‍♂️

**Comment by knadh** [comment]
webpack, sigh.

**Comment by gioppy** [comment]
Just a little update: with Webpack 5 everything works fine.
